# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

# demo:

rf_shades:
  pin: 12
  repeat: 3
  pause: 8064
  commands:
    open: "00010001"
    close: "00110011"
    stop: "01010101"
  init:
    len: 40
    time:
      high: 5000
      low: 2000
  bit:
    time:
      short: 340
      long: 690
# cover:
#   - platform: rf_shades
#     unique_id: rfCoverOffice
#     code: "10000101 00110001 11111000 10110001"
#     name: "office"
#   - platform: rf_shades
#     code: "10000101 00110001 01010010 10000001"
#     unique_id: rfCoverkitchen
#     name: "kitchen"
# up: "00010001",
# down: "00110011",
# stop: "01010101"
